services:
  bootstrapper:
    build: ./bootstrapper
    volumes:
      - ./keys:/keys
    command: npm start
  auth:
    build: ./auth
    ports:
      - "3001:3001"
    volumes:
      - ./keys:/keys
    depends_on:
      - bootstrapper
    command: npm start
  api:
    build: ./api
    ports:
      - "3002:3002"
    volumes:
      - ./keys:/keys
    depends_on:
      - auth
    command: npm start
  client:
    build: ./client
    depends_on:
      - api
    command: npm start