services:
  bootstrapper:
    build: ./bootstrapper
    volumes:
      - ./keys:/keys
    command: npm start
    profiles:
      - bootstrap
  auth:
    build: ./auth
    ports:
      - "3001:3001"
    volumes:
      - ./keys:/keys
    command: npm start
    profiles:
      - stack
  api:
    build: ./api
    ports:
      - "3002:3002"
    volumes:
      - ./keys:/keys
    depends_on:
      - auth
    command: npm start
    profiles:
      - stack
  client:
    build: ./client
    depends_on:
      - api
    volumes:
      - ./keys:/keys      
    command: npm start
    profiles:
      - stack